version: "3.8"

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 127.0.0.1:27017:27017
  app:
    build: .
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      MONGO_URI: "${MONGO_URI}"
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASS: "${MONGO_PASS}"
