version: "3.8"

services:

  app:
    build: .
    restart: always
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      MONGO_URI: "${MONGO_URI}"
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASS: "${MONGO_PASS}"
